# Generated by Django 3.1.5 on 2021-03-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=4096)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='donation date')),
                ('email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(max_length=80)),
                ('age', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=4096)),
                ('sex', models.CharField(max_length=10)),
                ('sterilization', models.BooleanField()),
                ('toilet', models.BooleanField()),
            ],
        ),
    ]
