# Generated by Django 3.1.5 on 2021-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='image_path',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='image_path',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
